accounts/urls.py
from django.urls import path
from accounts.views import *

app_name="accounts"

urlpatterns=[
    path("login/",login_user,name="login"),
    path("logout/",logout_user,name="logout"),
    path("register/",register_user,name="register")
]

ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("store.urls",namespace="store")),
    path("accounts/",include("accounts.urls",namespace="accounts"))
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import *
from accounts import views

app_name="store"
urlpatterns = [
    path("",views.login_user,name="index"),
    path("store/",store,name="items"),
    path("cart/",cart,name="cart"),
    path("checkout/",checkout,name="checkout"),
    path("product_info/<int:pk>",product_info,name="product_info"),
    path("update_cart/",UpdateCart,name="update_cart"),
    path("process_order/",ProcessOrder,name="process_order"),
    path("search_items/",search_items,name="search")
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    name=models.CharField(max_length=100,null=True)
    email=models.EmailField(null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name=models.CharField(max_length=100,null=True,blank=True)
    price = models.DecimalField(max_digits=7,decimal_places=2)
    digital=models.BooleanField(default=False,null=True,blank=True)
    image=models.ImageField(blank=True,null=True,upload_to="uploaded_pics")
    description=models.TextField(default='')
    stocks=models.IntegerField(default=10,null=True,blank=True)
    sales=models.IntegerField(default=0,null=True,blank=True)

    def __str__(self):
        return self.name

    @property
    def ImageURL(self):
        try:
            url=self.image.url
        except:
            url=''
        return url
    

class Order(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    date_ordered=models.DateTimeField(auto_now=True,blank=True,null=True)
    complete=models.BooleanField(default=False)
    transaction_id=models.CharField(max_length=100,null=True)

    def __str__(self):
        return str(self.pk)
    
    @property
    def get_cart_total(self):
        orderitems=self.cartitem_set.all()
        total=sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems=self.cartitem_set.all()
        total=sum([item.quantity for item in orderitems])
        return total

    @property
    def shipping(self):
        shipping=False
        cartitems=self.cartitem_set.all()

        for item in cartitems:
            if not item.product.digital:
                shipping=True
        return shipping


class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.SET_NULL,blank=True,null=True)
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
    quantity=models.IntegerField(default=0,blank=True,null=True)
    date_added=models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.date_added)

    @property
    def get_total(self):
        total=self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    order=models.ForeignKey(Order,on_delete=models.SET_NULL,blank=True,null=True)
    address=models.CharField(max_length=100,blank=True,null=True)
    city=models.CharField(null=True)
    state=models.CharField(null=True)
    zipcode=models.IntegerField(blank=True,null=True)
    date_added=models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.address

store/views.py
from django.shortcuts import render
from store.models import *
from django.views.generic import DetailView
from django.core.paginator import Paginator
from django.http import JsonResponse
import json
from datetime import datetime
from django.contrib.auth.decorators import login_required
# Create your views here.


def store(request):
    if request.user.is_authenticated:
        customer,created=Customer.objects.get_or_create(user=request.user)
        order,created=Order.objects.get_or_create(customer=customer,complete=False)
        items=order.cartitem_set.all() #one to many relationship
        cartitems=order.get_cart_items
    else:
        items=[]
        order={"get_cart_items":0,"get_cart_total":0,"shipping":False}
        cartitems=order["get_cart_items"]

    products=Product.objects.all()
    p=Paginator(products,3)
    page=request.GET.get("page")
    products=p.get_page(page)
    nums='a'* products.paginator.num_pages

    context={"products":products,"cartitems":cartitems,"nums":nums}
    return render(request,"store/store.html",context)


def search_items(request):
    if request.user.is_authenticated:
        customer,created=Customer.objects.get_or_create(user=request.user)
        order,created=Order.objects.get_or_create(customer=customer,complete=False)
        items=order.cartitem_set.all() #one to many relationship
        cartitems=order.get_cart_items
    else:
        items=[]
        order={"get_cart_items":0,"get_cart_total":0,"shipping":False}
        cartitems=order["get_cart_items"]

    keyword=request.POST.get("search")
    products=Product.objects.filter(name__icontains=keyword)
    count=products.count()

    p = Paginator(products, 3)
    page = request.GET.get("page")
    products = p.get_page(page)
    nums = 'a' * products.paginator.num_pages

    context={"products":products,"nums":nums,"count":count,"keyword":keyword,"cartitems":cartitems}
    return render(request,"store/search_items.html",context)


@login_required
def cart(request):
    if request.user.is_authenticated:
        customer,created=Customer.objects.get_or_create(user=request.user)
        order,created=Order.objects.get_or_create(customer=customer,complete=False)
        items=order.cartitem_set.all() #one to many relationship
        cartitems = order.get_cart_items

    else:
        items=[]
        order={"get_cart_items":0,"get_cart_total":0,"shipping":False}
        cartitems=order["get_cart_items"]


    context={"items":items,"order":order,"cartitems":cartitems}
    return render(request,"store/cart.html",context)


@login_required
def checkout(request):
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.cartitem_set.all()  # retrieving items from one to many relationship
        cartitems = order.get_cart_items
    else:
        items = []
        order = {"get_cart_items": 0, "get_cart_total": 0,"shipping":False}
        cartitems=order["get_cart_items"]

    context = {"items": items, "order": order,"cartitems":cartitems}
    return render(request,"store/checkout.html",context)


def product_info(request,pk):
    product=Product.objects.get(pk=pk)

    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(user=request.user)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.cartitem_set.all()  # retrieving items from one to many relationship
        cartitems = order.get_cart_items
    else:
        items = []
        order = {"get_cart_items": 0, "get_cart_total": 0}
        cartitems=order["get_cart_items"]

    context={"product":product,"cartitems":cartitems}
    return render(request,"store/product_detail.html",context)

#class ProductDetail(DetailView):
#    model=Product

#    def get_queryset(self,*args,**kwargs):
#        queryset=super().get_queryset(*args,**kwargs)
#         return queryset.filter(pk=self.kwargs.get("pk"))


@login_required
def UpdateCart(request):
    data=json.loads(request.body) #reading the json object
    productID=data["productID"]
    action = data["action"]
    print(f"Product: {productID}")
    print(f"Action: {action}")

    customer,created=Customer.objects.get_or_create(user=request.user)
    product=Product.objects.get(pk=productID)
    order,created=Order.objects.get_or_create(customer=customer,complete=False)
    cartitem,created=CartItem.objects.get_or_create(product=product,order=order)

    if action=="add":
        cartitem.quantity+=1
    elif action=="remove":
        cartitem.quantity-=1

    cartitem.save()

    if cartitem.quantity==0:
        cartitem.delete()

    return JsonResponse("Item was added",safe=False) # we send data from javascript to python using json


@login_required
def ProcessOrder(request):
    transaction_id=datetime.now().timestamp()
    data=json.loads(request.body)

    if request.user.is_authenticated:
        customer,created=Customer.objects.get_or_create(user=request.user)
        order,created=Order.objects.get_or_create(customer=customer,complete=False)

        total=float(data["user"]["total"])  # converts string data to float data cuz it's a dictionary
        order.transaction_id=transaction_id #updates the transaction_id field of order model

        if total == float(order.get_cart_total): #float is not the same as decimal. that's why we converted the cart total to float
            order.complete=True
            cartitems=order.cartitem_set.all()

            for item in cartitems:
                pk=item.product.pk
                product=Product.objects.get(pk=pk)
                product.sales+=1
                product.stocks-=1
                product.save()

        order.save()

        if order.shipping:
            ShippingAddress.objects.create(
                customer=customer,
                order=order,
                address=data["shipping"]["address"],
                city=data["shipping"]["city"],
                state=data["shipping"]["state"],
                zipcode=data["shipping"]["zipcode"]
            )
    else:
        print("User is not logged in.")

    return JsonResponse("Payment submitted...",safe=False) # we send data from javascript to python using json

store/templates/store/cart.html
{% extends "base.html" %}
{% load static %}
{% block title %}Cart{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="box-element">
        <a class="btn btn-outline-dark" href="{% url 'store:items' %}">Continue Shopping</a>
            <br>
            <br>
            <table class="table">
            <tr>
                <th><h5>Items: <strong>{{ order.get_cart_items }}</strong></h5></th>
                <th><h5>Total: <strong>$ {{ order.get_cart_total }}</strong></h5></th>
                <th><a href="{% url 'store:checkout' %}" class="btn btn-success" style="float: right;margin: 5px;">Checkout</a></th>
            </tr>
            </table>
        </div>
        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2;"></div>
                <div style="flex:2;"><strong>Item</strong></div>
                <div style="flex:1;"><strong>Price</strong></div>
                <div style="flex:1;"><strong>Quantity</strong></div>
                <div style="flex:1;"><strong>Total</strong></div>
            </div>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2;"><img class="row-image" src="{{ item.product.ImageURL }}"></div>
                <div style="flex:2;"><p>{{ item.product.name }}</p></div>
                <div style="flex:1;"><p>${{ item.product.price }}</p></div>
                <div style="flex:1;">
                    <p class="">{{ item.quantity }}</p>
                    <div class="quantity">
                       <img data-product="{{ item.product.pk }}" src="{% static 'images/arrow-up.png' %}" data-action="add" class="chg-quantity update-cart">
                       <img data-product="{{ item.product.pk }}" src="{% static 'images/arrow-down.png' %}"  data-action="remove" class="chg-quantity update-cart">
                    </div>
               </div>
               <div style="flex:1;"><p>${{ item.get_total }}</p></div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

store/templates/store/checkout.html
{% extends "base.html" %}
{% load static %}
{% block title %}Checkout{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                {% csrf_token %}
              <div id="user-info">
                <div class="form-field">
                    <input type="text" class="form-control" name="name" placeholder="Name..." required>
                </div>
                <div class="form-field">
                    <input type="email" class="form-control" name="email" placeholder="Email..." required>
                </div>
              </div>

              <div id="shipping-info">
                <hr>
                  <h5>Shipping Info</h5>
                  <div class="form-field">
                    <input type="text" class="form-control" name="address" placeholder="Address..." required>
                </div>
                  <div class="form-field">
                    <input type="text" class="form-control" name="city" placeholder="City..." required>
                </div>
                  <div class="form-field">
                    <input type="text" class="form-control" name="state" placeholder="State..." required>
                </div>
                  <div class="form-field">
                    <input type="text" class="form-control" name="zipcode" placeholder="Zip Code..." required>
                </div>
                  <div class="form-field">
                    <input type="text" class="form-control" name="country" placeholder="Country..." required>
                </div>
              </div>
                <hr>
                <button id="form-button" type="submit" class="btn btn-success btn-block">Continue</button>
            </form>

                <div class="box-element hidden" id="payment-info">
                    <small>Payment Options</small>
                    <!--<button id="make-payment">Make Payment</button>-->
                    <div id="paypal-button-container">
                    </div>
                </div>

        </div>
    </div>

    <div class="col-md-6">
        <div class="box-element">
            <a href="{% url 'store:cart' %}" class="btn btn-outline-dark">Back To Cart</a>
            <hr>
            <h3>Order Summary</h3>
            {% for item in items %}
            <div class="cart-row">
                <div style="flex:2;"><img class="row-image" src="{{ item.product.ImageURL }}"></div>
                <div style="flex:2;"><p>{{ item.product.name }}</p></div>
                <div style="flex:1;"><p>{{ item.product.price }}</p></div>
                <div style="flex:1;"><p class="">{{ item.quantity }}</p></div>
               <div style="flex:1;"><p>${{ item.get_total }}</p></div>
            </div>
            {% endfor %}
            <h5>Items: {{ order.get_cart_items }}</h5>
            <h5>Total: ${{ order.get_cart_total }}</h5>
        </div>
    </div>
</div>
 <script src="https://www.paypal.com/sdk/js?client-id=Aal67ntK9ZNmJWWXufrN9reRi4w1yy6r4T4N9ZHosqTuSq-mEcJGLahOVGHzdiCgjIT0qzVwKubuWhPi&currency=USD&disable-funding=credit"></script>

 <script>
    var total="{{ order.get_cart_total|floatformat:2 }}"
    // Render the PayPal button into #paypal-button-container
    paypal.Buttons({

        style: {
            color: "blue",
            shape: "rect"
        },

        // Set up the transaction
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: parseFloat(total).toFixed(2)
                    }
                }]
            });
        },

        // Finalize the transaction
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                // Show a success message to the buyer
                //alert('Transaction completed by ' + details.payer.name.given_name + '!');
                SubmitFormData()
            });
        }


    }).render('#paypal-button-container');
</script>

<script type="text/javascript">
var shipping="{{ order.shipping }}"
var total="{{ order.get_cart_total|floatformat:2 }}"

if (shipping===false){
    document.getElementById("shipping-info").inerHTML=''
}
if (user !== 'AnonymousUser')
{
		 	document.getElementById('user-info').innerHTML = ''
}

if (shipping === false && user !== 'AnonymousUser'){
			//Hide entire form if user is logged in and shipping is false
    document.getElementById('form-wrapper').classList.add("hidden");
				//Show payment if logged in user wants to buy an item that does not require shipping
    document.getElementById('payment-info').classList.remove("hidden");
}

var form=document.getElementById("form")



form.addEventListener("submit",function(e){
        e.preventDefault() //prevents from doing the default action
        console.log("Form submitted...")
        document.getElementById("form-button").classList.add("hidden")
        document.getElementById("payment-info").classList.remove("hidden")
    })

/* document.getElementById("make-payment").addEventListener("click",function(e) {
    SubmitFormData()
})*/

function SubmitFormData()
{
    console.log("Payment button clicked")

    var userFormData={
        "name":null,
        "email":null,
        "total":total
    }

    var shippingInfo={
        "address":null,
        "city":null,
        "state":null,
        "zipcode":null
    }

    if (shipping !== false) {
        shippingInfo.address = form.address.value
        shippingInfo.city = form.city.value
        shippingInfo.state = form.state.value
        shippingInfo.zipcode = form.zipcode.value
    }

    if (user==="AnonymousUser")
    {
        userFormData.name=form.name.value
        userFormData.email=form.email.value
    }
    console.log("Shipping Info: "+ shippingInfo)
    console.log("User Info: "+ userFormData)

    var url = "/process_order/" //goes to the url path of process_order

    fetch(url, {
		method:'POST',
		headers:{
			'Content-Type':'application/json',
			'X-CSRFToken':csrftoken,
		},
		body:JSON.stringify({'user':userFormData, 'shipping':shippingInfo}),

	})
	.then((response) => {response.json()})
	.then((data) => {
		  console.log('Success:', data);
		  alert('Transaction completed');
		  window.location.href = "{% url 'store:items' %}"
		})
}
</script>
{% endblock %}

store/templates/store/product_detail.html
{% extends "base.html" %}
{% load static %}
{% block  title %}Product Info{% endblock %}

{% block content %}
    <div class="row">
    <center>
        <div class="col-md-6">
            <img width="100%" src="{{ product.ImageURL }}">
            <div class="box-element product">
            <h5><strong>{{ product.name }}</strong></h5>
            <hr>
                <p>{{ product.description }}</p>
            <a href="{% url 'store:items' %}" class="btn btn-secondary">Back</a>
            <button data-product="{{ product.pk }}" data-action="add"  class="btn btn-secondary add-btn update-cart">Add To Cart</button>
            </div>
        </div>
    </center>
    </div>
{% endblock %}

store/templates/store/search_items.html
{% extends "base.html" %}
{% load  static %}
{% block title %}Main{% endblock %}

{% block content %}
<div class="row">
    <h3>You searched for {{ keyword }}...</h3>
    {% if count > 1 %}
    <h5>{{ count }} items found.</h5>
    {% else %}
     <h5>{{ count }} item found.</h5>
    {% endif %}

    {% if products %}
    {% for product in products %}
    <div class="col-md-4">
        <img class="thumbnail" src="{{ product.ImageURL }}">
        <div class="box-element product">
        <h5><strong>{{ product.name }}</strong></h5>
            <hr>
            <div>
            <small style="color:grey;display:inline-block;">Stocks: {{ product.stocks }}</small>
            <small style="color:grey;display:inline-block;float:right;margin-top:-1px;">Sales: {{ product.sales }}</small>
            </div>

            {% if user.is_authenticated %}
            <button data-product="{{ product.pk }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add To Cart</button>
            {% else %}
                <a  href="{% url 'accounts:login' %}" class="btn btn-outline-secondary add-btn">Add To Cart</a>
            {% endif %}

            <a href="{% url 'store:product_info' pk=product.pk %}" class="btn btn-outline-success">View</a>
            <h4 style="display: inline-block;float: right;">${{ product.price }}</h4>
        </div>
    </div>
    {% endfor %}
</div>
    <br>
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if products.has_previous %}
        <li class="page-item"><a class="page-link" href="?=page=1">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
    {% endif %}

    <!--<li class="page-item"><a class="page-link" href="#">Page {{ products.number }} of {{ products.paginator.num_pages }}</a></li>-->
    {% for n in nums %}
        {% if products.number == forloop.counter %}
            <li class="page-item"><a  style="background:#2E2E2E;color:white;" class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endif %}
    {% endfor %}

    {% if products.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ products.paginator.num_pages }}">Last &raquo;</a></li>
    {% endif %}
    </ul>
    </nav>
    {% else %}
        <br> <br> <br> <br> <br><br> <br> <br> <br> <br><br> <br> <br> <br> <br><br> <br> <br> <br> <br><br> <br> <br> <br> <br>
    {% endif %}
{% endblock %}

store/templates/store/store.html
{% extends "base.html" %}
{% load static %}
{% block title %}Main{% endblock %}

{% block content %}
<div class="row">
                {% for message in messages %}
                 <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
    {% for product in products %}
    <div class="col-md-4">
        <img class="thumbnail" src="{{ product.ImageURL }}">
        <div class="box-element product">
        <h5><strong>{{ product.name }}</strong></h5>
            <hr>
            <div>
            <small style="color:grey;display:inline-block;">Stocks: {{ product.stocks }}</small>
            <small style="color:grey;display:inline-block;float:right;margin-top:-1px;">Sales: {{ product.sales }}</small>
            </div>
            <br>
            {% if user.is_authenticated %}
            <button data-product="{{ product.pk }}" data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add To Cart</button>
            {% else %}
                <a  href="{% url 'accounts:login' %}" class="btn btn-outline-secondary add-btn">Add To Cart</a>
            {% endif %}

            <a href="{% url 'store:product_info' pk=product.pk %}" class="btn btn-outline-success">View</a>
            <h4 style="display: inline-block;float: right;">${{ product.price }}</h4>
        </div>
    </div>
    {% endfor %}
</div>
    <br>
    <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
    {% if products.has_previous %}
        <li class="page-item"><a class="page-link" href="?=page=1">&laquo; First</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a></li>
    {% endif %}

    <!--<li class="page-item"><a class="page-link" href="#">Page {{ products.number }} of {{ products.paginator.num_pages }}</a></li>-->
    {% for n in nums %}
        {% if products.number == forloop.counter %}
            <li class="page-item"><a style="background:#2E2E2E;color:white;" class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
            {% else %}
        <li class="page-item"><a class="page-link" href="?page={{ forloop.counter }}">{{ forloop.counter }}</a></li>
        {% endif %}
    {% endfor %}

    {% if products.has_next %}
        <li class="page-item"><a class="page-link" href="?page={{ products.next_page_number }}">Next</a></li>
        <li class="page-item"><a class="page-link" href="?page={{ products.paginator.num_pages }}">Last &raquo;</a></li>
    {% endif %}
    </ul>
    </nav>
{% endblock %}