accounts/urls.py
from django.urls import path
from accounts.views import *

app_name="accounts"

urlpatterns=[
    path("login/",login_user,name="login"),
    path("logout/",logout_user,name="logout"),
    path("register/",register_user,name="register")
]

ecom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("store.urls",namespace="store")),
    path("accounts/",include("accounts.urls",namespace="accounts"))
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import *
from accounts import views

app_name="store"
urlpatterns = [
    path("",views.login_user,name="index"),
    path("store/",store,name="items"),
    path("cart/",cart,name="cart"),
    path("checkout/",checkout,name="checkout"),
    path("product_info/<int:pk>",product_info,name="product_info"),
    path("update_cart/",UpdateCart,name="update_cart"),
    path("process_order/",ProcessOrder,name="process_order"),
    path("search_items/",search_items,name="search")
]

templates/base.html
{% load static %}

<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">

<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

<script type="text/javascript">
    var user="{{ user }}"
    
    function getToken(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getToken('csrftoken');
</script>
</head>

<body>
{% include "navbar.html" %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<footer>&copy; Shoppers 2025. All rights reserved.</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/js/bootstrap.bundle.min.js" integrity="sha384-j1CDi7MgGQ12Z7Qab0qlWQ/Qqz24Gc6BM0thvEMVjHnfYGF0rmFCozFSxQBxwHKO" crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static 'js/cart.js' %}" ></script>
</body>
</html>

templates/footer.html
<footer>&copy; Shoppers 2025. All rights reserved.</footer>

templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme='dark'>
  <div class="container-fluid">
    <a style="margin-left:10px;" class="navbar-brand" href="{% url 'store:index' %}"><strong>SHOPPERS</strong> <i class="bi bi-bag-check-fill" style="font-size: 1.5rem;"></i></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'store:items' %}">Home</a>
        </li>
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'accounts:logout' %}">Logout</a>
        </li>
          {% endif %}
      </ul>
        {% if user.is_authenticated %}
            <span style="color:white;">Hello, {{ user }}!</span>
            {% else %}
        <small><a class="register" href="{% url 'accounts:register' %}">Register</a></small>
        {% endif %}
      <form id="search" class="d-flex" role="search" action="{% url 'store:search' %}" method="POST">
          {% csrf_token %}
        <input class="form-control me-2" type="search" name="search" placeholder="Find..." aria-label="Search"/ required>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
        
        <div class="form-inline my-2 my-lg-0">
            {% if not user.is_authenticated %}
       <a id="login-btn" href="{% url 'accounts:login' %}" class="btn btn-warning">Login</a>
         
         {% else %}
       <a href="{% url 'store:cart' %}">
         <img  id="cart-icon" src="{% static 'images/cart.png' %}">
        </a>
            
       <p id="cart-total">{{ cartitems }}</p>
         {% endif %}

    </div>
    </div>
  </div>
</nav>